apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signing-cert
spec:
  secretName: signing-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "wa-playeconomy.eastus.cloudapp.azure.com"
